// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZair9D4Ny7zQCX2P7_7V5laFCvwVrpw',
    authDomain: 'aflbizprocess.firebaseapp.com',
    projectId: 'aflbizprocess',
    storageBucket: 'aflbizprocess.appspot.com',
    messagingSenderId: '132336645051',
    appId: '1:132336645051:web:2788a0e60283c3a4100a9e',
    measurementId: 'G-R5KLRTZYWH'
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyBY0jBEBpba6lyhAbXLvJMHThKOGU-fPis',
      appId: '1:132336645051:android:471ceb53bef98157100a9e',
      messagingSenderId: '132336645051',
      projectId: 'aflbizprocess',
      storageBucket: 'aflbizprocess.appspot.com');
}
